export interface IDocument {
  _id: string;
  /** Optional; some APIs only return _id. Prefer _id for identity. */
  id?: string;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
}
export interface IAssetBucket {
  name: string;
  url: string;
  path: string;
}

export interface IUser extends IDocument {
  _id: string;
  name: string;
  email: string;
  /** Profile image URL. Often omitted or empty from API. */
  image?: string;
  role: string;
  /** ISO country code. May be omitted. */
  country?: string;
  /** IANA timezone. May be omitted. */
  timezone?: string;
  /** Language code. May be omitted. */
  language?: string;
  /** Currency code. May be omitted. */
  currency?: string;
  attributes?: Record<string, string | number | boolean>;
}

export interface IAsset extends IDocument {
  _id: string;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
  name: string; // original name
  uniqueName: string; // unique name generated by multer
  mimeType: string; // mime type
  size: number; // size in bytes
  encoding: string; // encoding
  bucket: {
    name: string;
    url: string;
    path: string;
  };
  metadata: {
    [key: string]: string | number | boolean | object | null;
  };
  // image only
  image?: {
    width: number;
    height: number;
  };
  tags: string[];
  public: boolean;
  creator: string | IUser;
}

// Subscription Management Types
export type BillingInterval = 'monthly' | 'yearly' | 'quarterly';

/** Billing interval constants */
export const BillingIntervals = {
  Monthly: 'monthly',
  Yearly: 'yearly',
  Quarterly: 'quarterly',
} as const;

/** Subscription status constants */
export const SubscriptionStatus = {
  Active: 'active',
  Trialing: 'trialing',
  Canceled: 'canceled',
  PastDue: 'past_due',
  Paused: 'paused',
  Incomplete: 'incomplete',
  Unpaid: 'unpaid',
} as const;

export type SubscriptionStatusType = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];

/** Invoice status constants */
export const InvoiceStatuses = {
  Draft: 'draft',
  Open: 'open',
  Paid: 'paid',
  Uncollectible: 'uncollectible',
  Void: 'void',
} as const;

/** Subscription item type constants */
export const SubscriptionItemType = {
  Feature: 'feature',
  Limit: 'limit',
  Quota: 'quota',
} as const;

/** Dunning state constants */
export const DunningState = {
  None: 'none',
  Notified: 'notified',
  Warning: 'warning',
  Final: 'final',
  Suspended: 'suspended',
} as const;

export interface ISubscription {
  _id: string;
  subscriptionStatus: SubscriptionStatusType;
  stripePriceId?: string;
  stripeCurrentPeriodEnd?: string; // ISO date string for when current billing period ends
  cancelAtPeriodEnd: boolean;
  billingInterval?: BillingInterval;
  /** Trial start date (ISO string). Set when subscription is in trial. */
  trialStart?: string;
  /** Trial end date (ISO string). Set when subscription is in trial. */
  trialEnd?: string;
  /** When the subscription was canceled (ISO string). Soft-delete marker. */
  canceledAt?: string;
  /** Dunning state: 'none', 'notified', 'warning', 'final', 'suspended'. */
  dunningState?: string;
  /** Whether this subscription uses per-seat pricing. */
  seatPricingEnabled?: boolean;
  /** Current billable seat count. */
  currentSeatCount?: number;
  createdAt: string;
  updatedAt: string;
  plan?: {
    _id: string;
    name: string;
    slug: string;
    description?: string;
    /** Stripe currency code (e.g. 'usd', 'inr', 'eur'). */
    currency?: string;
  };
}

export interface ISubscriptionItem {
  _id: string;
  type: 'feature' | 'limit' | 'quota';
  name: string;
  slug: string;
  description?: string;
  category: string;
}

/** Per-interval quota value (plan-group/versions and public plans schema). */
export interface IQuotaIntervalValue {
  included: number;
  /** Overage price in cents. Omitted in public plans; use pricingVariant.quotaOverages for display. */
  overage?: number;
  /** Stripe price ID for overage. Omitted in public plans; use pricingVariant.quotaOveragePriceIds. */
  priceId?: string;
  /** Unit size for overage pricing (e.g. 1000 = price per 1000 units). */
  unitSize?: number;
}

/** Quota defined per billing interval (new plan-group/versions schema) */
export interface IQuotaByInterval {
  /** Whether over-usage beyond included is allowed (billed as overage). When false, usage is hard-capped at included amount. Default true. */
  allowOverage?: boolean;
  monthly?: IQuotaIntervalValue;
  yearly?: IQuotaIntervalValue;
  quarterly?: IQuotaIntervalValue;
}

/** Base pricing per interval. Values are often in cents (Stripe); convert for display. */
export interface IBasePricing {
  monthly: number;
  yearly: number;
  quarterly: number;
}

/** Stripe price IDs per billing interval (for a single currency variant). */
export interface IStripePricesByInterval {
  monthlyPriceId?: string;
  yearlyPriceId?: string;
  quarterlyPriceId?: string;
  monthly?: string;
  yearly?: string;
}

/** Overage amounts in cents per interval, keyed by quota slug. Used in pricing variants. */
export type IQuotaOveragesByInterval = Record<
  string,
  { monthly?: number; yearly?: number; quarterly?: number }
>;

/** Overage Stripe price IDs per interval, keyed by quota slug. Used in pricing variants. */
export type IQuotaOveragePriceIdsByInterval = Record<
  string,
  { monthly?: string; yearly?: string; quarterly?: string }
>;

/**
 * Multi-currency pricing variant at plan version level.
 * Each plan version can have multiple variants (e.g. usd, eur, inr, sgd).
 */
export interface IPricingVariant {
  _id: string;
  currency: string;
  basePricing: IBasePricing;
  stripePrices: IStripePricesByInterval;
  /** Per-seat pricing config. When enabled, a second recurring item is on the subscription. */
  seatPricing?: {
    enabled: boolean;
    includedSeats: number;
    /** Maximum seats allowed. 0 or undefined = unlimited. */
    maxSeats?: number;
    perSeat: IBasePricing;
  };
  /** Stripe Price IDs for the per-seat recurring price. */
  seatStripePrices?: IStripePricesByInterval;
  /** Overage cents per quota slug per interval. */
  quotaOverages?: IQuotaOveragesByInterval;
  /** Stripe price IDs for overage per quota slug per interval. */
  quotaOveragePriceIds?: IQuotaOveragePriceIdsByInterval;
}

export interface IPlanVersion {
  _id: string;
  version: number;
  name: string;
  status: 'draft' | 'published';
  features?: Record<string, boolean>;
  limits?: Record<string, number>;
  /** Per-interval quotas (included, unitSize; overage from pricingVariant.quotaOverages). */
  quotas?: Record<string, IQuotaByInterval>;
  /** Multi-currency pricing. Each variant has currency, basePricing, stripePrices, quotaOverages. */
  pricingVariants?: IPricingVariant[];
  subscriptionItems?: ISubscriptionItem[];
  isCurrent?: boolean;
  isLegacy?: boolean;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
  stripeProductId?: string;
}

/** Plan version summary (e.g. plan.latestVersion from subscription API) with subscriptionItems as IDs. */
export interface IPlanVersionSummary extends Omit<IPlanVersion, 'subscriptionItems'> {
  subscriptionItems?: string[];
}

export interface IPlan {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  /** Stripe currency code (e.g. 'usd', 'inr', 'eur'). Used for pricing display. */
  currency?: string;
  /** Freemium plan: $0 base pricing, no seat billing, no trial. */
  isFreemium?: boolean;
  latestVersion?: IPlanVersionSummary;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}

export interface IPlanGroupLatestVersion {
  _id: string;
  version: number;
  planVersionIds: string[];
  requiredItems: string[];
  status: 'draft' | 'published';
  isCurrent?: boolean;
  isLegacy?: boolean;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  description?: string;
}

export interface IPlanGroup {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  latestVersion?: IPlanGroupLatestVersion;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}

export interface IPlanGroupVersion {
  _id: string;
  version: number;
  description?: string;
  group?: {
    _id: string;
    name: string;
    description?: string;
  };
  planVersionIds: IPlanVersionWithPlan[] | string[];
  requiredItems?: string[];
  status?: 'draft' | 'published';
  isCurrent?: boolean;
  isLegacy?: boolean;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}

export interface ISubscriptionResponse {
  subscription: ISubscription | null;
  planVersion: IPlanVersion | null;
  plan: IPlan | null;
  group: IPlanGroup | null;
  groupVersion: IPlanGroupVersion | null;
}

/** Plan version with nested plan info (name, slug, currency for display). */
export interface IPlanVersionWithPlan extends IPlanVersion {
  plan: IPlan;
}

/**
 * Plan group version with full plan versions (for GET .../plan-group/versions).
 * Each plan has plan, subscriptionItems, quotas (per-interval), pricingVariants.
 */
export interface IPlanGroupVersionWithPlans {
  _id: string;
  version: number;
  description?: string;
  /** Full plan versions with nested plan (name, slug, currency). */
  plans: IPlanVersionWithPlan[];
  isCurrent?: boolean;
  whatsNew?: {
    newPlans: IPlanVersionWithPlan[];
    updatedPlans: IPlanVersionWithPlan[];
    removedPlans: IPlanVersionWithPlan[];
  };
}

export interface IPlanGroupInfo {
  _id: string;
  name: string;
  slug: string;
  description?: string;
}

/** Response from GET workspaces/:id/subscription/plan-group (and by version). */
export interface IPlanGroupResponse {
  /** Plan group with latestVersion, archived, deleted, timestamps. May be null in some API responses. */
  group: IPlanGroup | null;
  /** Current group version with populated planVersionIds (or IDs). */
  groupVersion: IPlanGroupVersion;
  /** Full plan versions for display (subscriptionItems, pricingVariants, quotas). */
  plans: IPlanVersionWithPlan[];
}

/**
 * Response from GET workspaces/:workspaceId/subscription/plan-group/versions.
 * Group summary plus current and available group versions; each version has plans with
 * per-interval quotas and pricingVariants.
 */
export interface IPlanGroupVersionsResponse {
  /** Plan group summary (_id, name, slug). */
  group: IPlanGroupInfo;
  /** Current group version (user's version when subscribed, or latest published when not). */
  currentVersion: IPlanGroupVersionWithPlans;
  /** Newer versions when user has subscription; empty when no subscription. */
  availableVersions: IPlanGroupVersionWithPlans[];
}

/** Request body for POST .../workspaces/:id/subscription/checkout. Only these fields are allowed. */
export interface ICheckoutSessionRequest {
  planVersionId: string;
  billingInterval?: BillingInterval;
  currency?: string;
  successUrl?: string;
  cancelUrl?: string;
}

export interface ICheckoutSessionResponse {
  /** Response type discriminator. Added for centralized checkout flow. */
  type?: 'checkout' | 'trial_started' | 'existing';
  success: boolean;
  checkoutUrl: string;
  sessionId: string;
  message: string;
  planVersion?: {
    _id: string;
    version: number;
    name: string;
  };
}

/** No-card trial started server-side; no redirect needed. */
export interface ICheckoutTrialResult {
  type: 'trial_started';
  success: boolean;
  checkoutUrl: null;
  sessionId: null;
  subscription: ISubscription;
  message: string;
}

/** Workspace already has a matching active subscription. */
export interface ICheckoutExistingResult {
  type: 'existing';
  success: boolean;
  checkoutUrl: null;
  sessionId: null;
  message: string;
  existingSubscription?: {
    _id: string;
    subscriptionStatus: string;
    stripePriceId?: string;
  };
}

/**
 * Discriminated union for POST /subscription/checkout responses.
 * - `checkout`: Stripe checkout session created, redirect user to checkoutUrl
 * - `trial_started`: No-card trial started server-side, no redirect needed
 * - `existing`: Workspace already has a matching subscription
 */
export type CheckoutResult =
  | (ICheckoutSessionResponse & { type: 'checkout' })
  | ICheckoutTrialResult
  | ICheckoutExistingResult;

/** Request body for PATCH .../workspaces/:id/subscription. Only these fields are allowed. */
export interface ISubscriptionUpdateRequest {
  planVersionId: string;
  billingInterval?: BillingInterval;
  successUrl?: string;
  cancelUrl?: string;
}

export interface ISubscriptionUpdateResponse {
  _id: string;
  subscriptionStatus: string;
  workspace: string;
  planVersion: string;
  plan: string;
  planGroup?: string;
  planGroupVersion?: string;
  cancelAtPeriodEnd: boolean;
  createdAt: string;
  updatedAt: string;
}

// Public Plans Response (for pricing page - no auth required)
export interface IPublicPlanItemCategory {
  name: string;
  slug: string;
}

export interface IPublicPlanItem {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  type: 'feature' | 'limit' | 'quota';
  category: IPublicPlanItemCategory;
}

/**
 * Public plan version (e.g. from GET /api/v1/public/:orgId/plans/:slug).
 * Each plan has _id, name (plan display name), version, status, pricingVariants, quotas, features, limits.
 * Pricing is in cents (see response.notes).
 */
export interface IPublicPlanVersion {
  _id: string;
  /** Plan display name (e.g. "Pro", "Base Plan"). */
  name: string;
  version: number;
  status: 'draft' | 'published';
  /** Multi-currency pricing. Use getBasePriceCents(plan, currency, interval) and getQuotaDisplayWithVariant for display. */
  pricingVariants?: IPricingVariant[];
  /** Keyed by item slug. Per-interval: included, unitSize; overage from pricingVariant.quotaOverages. */
  quotas: Record<string, IQuotaByInterval>;
  features: Record<string, boolean>;
  limits: Record<string, number>;
}

export interface IPublicPlansResponse {
  items: IPublicPlanItem[];
  plans: IPublicPlanVersion[];
  /** Optional note from API (e.g. "Pricing is in cents. Please convert to dollars for display."). */
  notes?: string;
}

// Invoice Types
export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'uncollectible' | 'void';

export interface IInvoice {
  id: string;
  amount_due: number; // Amount in cents
  number: string | null;
  amount_paid: number; // Amount in cents
  currency: string; // e.g., 'usd'
  status: InvoiceStatus;
  created: number; // Unix timestamp
  due_date: number | null; // Unix timestamp or null
  hosted_invoice_url: string; // Stripe hosted invoice URL
  invoice_pdf: string | null; // PDF download URL or null
  description: string | null; // Invoice description
  subscription: string; // Subscription ID
}

export interface IInvoiceListResponse {
  success: boolean;
  invoices: IInvoice[];
  has_more: boolean;
}

export interface IInvoiceResponse {
  success: boolean;
  invoice: IInvoice;
}

// Quota Usage Types

/** Request body for POST .../workspaces/:id/subscription/usage */
export interface IRecordUsageRequest {
  quotaSlug: string;
  quantity: number;
  metadata?: Record<string, unknown>;
  source?: string;
  idempotencyKey?: string;
}

/** Response from POST .../workspaces/:id/subscription/usage */
export interface IRecordUsageResponse {
  used: number;
  consumed: number;
  included: number;
  available: number;
  overage: number;
  billedAsync: boolean;
}

/** Single quota usage status (shared between status and all endpoints). */
export interface IQuotaUsageStatus {
  consumed: number;
  included: number;
  available: number;
  overage: number;
  hasOverage: boolean;
  /** Whether over-usage is allowed (billed as overage). When false, usage is hard-capped. Default true. */
  allowOverage?: boolean;
}

/** Response from GET .../workspaces/:id/subscription/usage/status?quotaSlug=X */
export interface IQuotaUsageStatusResponse extends IQuotaUsageStatus {
  quotaSlug: string;
}

/** Response from GET .../workspaces/:id/subscription/usage/all */
export interface IAllQuotaUsageResponse {
  quotas: Record<string, IQuotaUsageStatus>;
}

/** Single usage log entry from GET .../usage/logs */
export interface IUsageLogEntry {
  _id: string;
  quotaSlug: string;
  quantity: number;
  source?: string;
  workspace: string;
  createdAt: string;
  updatedAt: string;
}

/** Query parameters for GET .../workspaces/:id/subscription/usage/logs */
export interface IUsageLogsQuery {
  quotaSlug?: string;
  from?: string;
  to?: string;
  source?: string;
  page?: number;
  limit?: number;
}

/** Paginated response from GET .../workspaces/:id/subscription/usage/logs */
export interface IUsageLogsResponse {
  docs: IUsageLogEntry[];
  totalDocs: number;
  limit: number;
  page: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPrevPage: boolean;
}
