export interface IDocument {
  _id: string;
  /** Optional; some APIs only return _id. Prefer _id for identity. */
  id?: string;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
}
export interface IAssetBucket {
  name: string;
  url: string;
  path: string;
}

export interface IUser extends IDocument {
  _id: string;
  name: string;
  email: string;
  /** Profile image URL. Often omitted or empty from API. */
  image?: string;
  role: string;
  /** ISO country code. May be omitted. */
  country?: string;
  /** IANA timezone. May be omitted. */
  timezone?: string;
  /** Language code. May be omitted. */
  language?: string;
  /** Currency code. May be omitted. */
  currency?: string;
  attributes?: Record<string, string | number | boolean>;
}

export interface IAsset extends IDocument {
  _id: string;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
  name: string; // original name
  uniqueName: string; // unique name generated by multer
  mimeType: string; // mime type
  size: number; // size in bytes
  encoding: string; // encoding
  bucket: {
    name: string;
    url: string;
    path: string;
  };
  metadata: {
    [key: string]: string | number | boolean | object | null;
  };
  // image only
  image?: {
    width: number;
    height: number;
  };
  tags: string[];
  public: boolean;
  creator: string | IUser;
}

// Subscription Management Types
export type BillingInterval = 'monthly' | 'yearly' | 'quarterly';

export interface ISubscription {
  _id: string;
  subscriptionStatus: 'active' | 'trialing' | 'canceled' | 'past_due';
  stripePriceId?: string;
  stripeCurrentPeriodEnd?: string; // ISO date string for when current billing period ends
  cancelAtPeriodEnd: boolean;
  billingInterval?: BillingInterval;
  createdAt: string;
  updatedAt: string;
  plan?: {
    _id: string;
    name: string;
    slug: string;
    description?: string;
  };
}

export interface ISubscriptionItem {
  _id: string;
  type: 'feature' | 'limit' | 'quota';
  name: string;
  slug: string;
  description?: string;
  category: string;
}

export interface IQuotaValue {
  included: number;
  overage?: number;
  stripePriceId?: string;
}

/** Per-interval quota value (new plan-group/versions schema) */
export interface IQuotaIntervalValue {
  included: number;
  overage: number;
  priceId: string;
  /** Optional unit size for overage pricing (e.g. 1000 = price per 1000 units). */
  unitSize?: number;
}

/** Quota defined per billing interval (new plan-group/versions schema) */
export interface IQuotaByInterval {
  monthly?: IQuotaIntervalValue;
  yearly?: IQuotaIntervalValue;
  quarterly?: IQuotaIntervalValue;
}

/** Base pricing per interval. Values are often in cents (Stripe); convert for display. */
export interface IBasePricing {
  monthly: number;
  yearly: number;
  quarterly: number;
}

export interface IPlanVersion {
  _id: string;
  version: number;
  name: string;
  status: 'draft' | 'published';
  features?: Record<string, boolean>;
  limits?: Record<string, number>;
  /** Legacy: number | IQuotaValue. New schema: IQuotaByInterval (per-interval included/overage/priceId) */
  quotas?: Record<string, number | IQuotaValue | IQuotaByInterval>;
  basePricing?: IBasePricing;
  stripePrices?: {
    monthlyPriceId?: string;
    yearlyPriceId?: string;
    quarterlyPriceId?: string;
    monthly?: string;
    yearly?: string;
  };
  subscriptionItems?: ISubscriptionItem[];
  isCurrent?: boolean;
  isLegacy?: boolean;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
  stripeProductId?: string;
}

/** Plan version summary (e.g. plan.latestVersion from subscription API) with subscriptionItems as IDs. */
export interface IPlanVersionSummary extends Omit<IPlanVersion, 'subscriptionItems'> {
  subscriptionItems?: string[];
}

export interface IPlan {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  latestVersion?: IPlanVersionSummary;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}

export interface IPlanGroupLatestVersion {
  _id: string;
  version: number;
  planVersionIds: string[];
  requiredItems: string[];
  status: 'draft' | 'published';
  isCurrent?: boolean;
  isLegacy?: boolean;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  description?: string;
}

export interface IPlanGroup {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  latestVersion?: IPlanGroupLatestVersion;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}

export interface IPlanGroupVersion {
  _id: string;
  version: number;
  description?: string;
  group?: {
    _id: string;
    name: string;
    description?: string;
  };
  planVersionIds: IPlanVersionWithPlan[] | string[];
  requiredItems?: string[];
  status?: 'draft' | 'published';
  isCurrent?: boolean;
  isLegacy?: boolean;
  archived?: boolean;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}

export interface ISubscriptionResponse {
  subscription: ISubscription | null;
  planVersion: IPlanVersion | null;
  plan: IPlan | null;
  group: IPlanGroup | null;
  groupVersion: IPlanGroupVersion | null;
}

export interface IPlanVersionWithPlan extends IPlanVersion {
  plan: IPlan;
}

export interface IPlanGroupVersionWithPlans {
  _id: string;
  version: number;
  description?: string;
  plans: IPlanVersionWithPlan[];
  isCurrent?: boolean;
  whatsNew?: {
    newPlans: IPlanVersionWithPlan[];
    updatedPlans: IPlanVersionWithPlan[];
    removedPlans: IPlanVersionWithPlan[];
  };
}

export interface IPlanGroupInfo {
  _id: string;
  name: string;
  slug: string;
  description?: string;
}

/** Response from GET workspaces/:id/subscription/plan-group (and by version). */
export interface IPlanGroupResponse {
  /** Plan group with latestVersion, archived, deleted, timestamps. */
  group: IPlanGroup;
  /** Current group version with populated planVersionIds (or IDs). */
  groupVersion: IPlanGroupVersion;
  /** Full plan versions for display (subscriptionItems, basePricing, quotas, etc.). */
  plans: IPlanVersionWithPlan[];
}

export interface IPlanGroupVersionsResponse {
  group: IPlanGroupInfo;
  currentVersion: IPlanGroupVersionWithPlans;
  availableVersions: IPlanGroupVersionWithPlans[];
}

export interface ICheckoutSessionRequest {
  planVersionId: string;
  billingInterval?: BillingInterval;
  successUrl?: string;
  cancelUrl?: string;
}

export interface ICheckoutSessionResponse {
  success: boolean;
  checkoutUrl: string;
  sessionId: string;
  message: string;
  planVersion?: {
    _id: string;
    version: number;
    name: string;
  };
}

export interface ISubscriptionUpdateRequest {
  planVersionId: string;
  billingInterval?: BillingInterval;
  successUrl?: string;
  cancelUrl?: string;
}

export interface ISubscriptionUpdateResponse {
  _id: string;
  subscriptionStatus: string;
  workspace: string;
  planVersion: string;
  plan: string;
  planGroup?: string;
  planGroupVersion?: string;
  cancelAtPeriodEnd: boolean;
  createdAt: string;
  updatedAt: string;
}

// Public Plans Response (for pricing page - no auth required)
export interface IPublicPlanItemCategory {
  name: string;
  slug: string;
}

export interface IPublicPlanItem {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  type: 'feature' | 'limit' | 'quota';
  category: IPublicPlanItemCategory;
}

export interface IPublicPlanPricing {
  monthly: number;
  yearly: number;
  quarterly: number;
}

export interface IPublicPlanQuotaValue {
  included: number;
  overage: number;
  stripePriceId?: string;
}

/**
 * Public plan version (e.g. from GET /api/v1/public/:orgId/plans/:slug).
 * Pricing is typically in cents; convert to dollars for display (see response.notes).
 * Quotas may be flat (legacy) or per-interval (monthly/yearly/quarterly with priceId, unitSize).
 */
export interface IPublicPlanVersion {
  _id: string;
  name: string;
  version: number;
  status: 'draft' | 'published';
  /** Prices per interval (usually in cents). */
  pricing: IPublicPlanPricing;
  /** Keyed by item slug. Value is flat (legacy) or per-interval (IQuotaByInterval). Use getQuotaDisplayValue(plan.quotas[slug], interval) for display. */
  quotas: Record<string, IPublicPlanQuotaValue | IQuotaByInterval>;
  features: Record<string, boolean>;
  limits: Record<string, number>;
}

export interface IPublicPlansResponse {
  items: IPublicPlanItem[];
  plans: IPublicPlanVersion[];
  /** Optional note from API (e.g. "Pricing is in cents. Please convert to dollars for display."). */
  notes?: string;
}

// Invoice Types
export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'uncollectible' | 'void';

export interface IInvoice {
  id: string;
  amount_due: number; // Amount in cents
  number: string | null;
  amount_paid: number; // Amount in cents
  currency: string; // e.g., 'usd'
  status: InvoiceStatus;
  created: number; // Unix timestamp
  due_date: number | null; // Unix timestamp or null
  hosted_invoice_url: string; // Stripe hosted invoice URL
  invoice_pdf: string | null; // PDF download URL or null
  description: string | null; // Invoice description
  subscription: string; // Subscription ID
}

export interface IInvoiceListResponse {
  success: boolean;
  invoices: IInvoice[];
  has_more: boolean;
}

export interface IInvoiceResponse {
  success: boolean;
  invoice: IInvoice;
}
